name: Build NgHauMenuApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Unzip project
        run: unzip NgHauMenuApp.zip -d NgHauMenuApp

      - name: Build with Gradle
        run: |
          cd NgHauMenuApp
          chmod +x ./gradlew || true
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NgHauMenuApp
          path: NgHauMenuApp/app/build/outputs/apk/debug/*.apk
